kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: primazactl-worker-test
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: "ClusterConfiguration"
        apiServer:
          extraArgs:
            anonymous-auth: "true"
