PRIMAZA_CONFIG: str = "control_plane_config"
WORKER_CONFIG: str = "crds_config"
APP_AGENT_CONFIG: str = "application_namespace_config"
SVC_AGENT_CONFIG: str = "service_namespace_config"
REPOSITORY: str = "mmulholla/primaza"
