name: Create fake release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "create a fake version for primazctl testing"
        required: true
        default: "latest"

jobs:
  create_fake_release:
    name: Create fake release
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ github.event.inputs.version }}
      PRIMAZA_CONFIG_FILE: primaza_main_config_${{ github.event.inputs.version }}.yaml
      WORKER_CONFIG_FILE: primaza_worker_config_${{ github.event.inputs.version }}.yaml
      APPLICATION_AGENT_CONFIG_FILE: application_agent_config_${{ github.event.inputs.version }}.yaml
      SERVICE_AGENT_CONFIG_FILE: service_agent_config_${{ github.event.inputs.version }}.yaml
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: run build
        run: make all

      - name: Create the release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          body: "Release for testing purposes only"
          files: |
            ${{ env.PRIMAZA_CONFCONFIG_FILE }}
            ${{ env.WORKER_CONFIG_FILE }}
            ${{ env.APPLICATION_AGENT_CONFIG_FILE }}
            ${{ env.SERVICE_AGENT_CONFIG_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
