name: Release primazactl

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      version:
        description: "create a version for primazctl"
        required: true
        default: "latest"

permissions:
  contents: write

jobs:
  build:
    name: Deploy releases for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Version and Manifests
        run: |
          # set version based on dispatch type
          version="latest"
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            version=${{ github.event.inputs.version }}
          elif [[ "${{github.ref_type}}" == "tag" ]]; then
            version=${{ github.ref_name }}
          fi
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "PRIMAZA_CTL_VERSION=$version" >> $GITHUB_ENV
          echo "PRIMAZA_CONFIG_FILE=primaza_main_config_$version.yaml" >> $GITHUB_ENV
          echo "WORKER_CONFIG_FILE=primaza_worker_config_$version.yaml" >> $GITHUB_ENV
          echo "APPLICATION_AGENT_CONFIG_FILE=application_agent_config_$version.yaml" >> $GITHUB_ENV
          echo "SERVICE_AGENT_CONFIG_FILE=service_agent_config_$version.yaml" >> $GITHUB_ENV

      - name: Test and make manifests
        id: test-and-manifests
        run: |
          # run make test-local to test and create manifests
          make test-local

      - name: Build binary
        run: make single-binary

      - name: Delete previous release and tag
        if: ${{ env.VERSION == 'latest' }}
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true # default: false
          tag_name: ${{ env.VERSION }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Release for tag event
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          body: "Release version ${{ env.VERSION }}"
          draft: true
          generate_release_notes: true
          files: |
            ./out/venv3/dist/primazactl
            ${{ env.PRIMAZA_CONFIG_FILE }}
            ${{ env.WORKER_CONFIG_FILE }}
            ${{ env.APPLICATION_AGENT_CONFIG_FILE }}
            ${{ env.SERVICE_AGENT_CONFIG_FILE }}

      - name: Release for non tag events
        if: ${{ github.ref_type != 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          body: "Release version ${{ env.VERSION }}"
          draft: true
          generate_release_notes: true
          files: |
            ./out/venv3/dist/primazactl
            ${{ env.PRIMAZA_CONFIG_FILE }}
            ${{ env.WORKER_CONFIG_FILE }}
            ${{ env.APPLICATION_AGENT_CONFIG_FILE }}
            ${{ env.SERVICE_AGENT_CONFIG_FILE }}
